<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1CCS179" failures="1" tests="2" name="Test" time="48.339" errors="0" timestamp="2022-08-22T20:50:29 IST">
  <testcase classname="com.qa.testLayer.TradingTest" name="buyShareAxis" time="10.14"/>
  <testcase classname="com.qa.testLayer.TradingTest" name="buyShareWipro" time="10.218">
    <failure type="java.lang.AssertionError" message="expected [Order Created successfully] but found [Order Created ccessfully]">
      <![CDATA[java.lang.AssertionError: expected [Order Created successfully] but found [Order Created ccessfully]
at com.qa.testLayer.TradingTest.buyShareWipro(TradingTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- buyShareWipro -->
</testsuite> <!-- Test -->
